/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "dgiBanking_constants.h"

namespace dgi {

const dgiBankingConstants g_dgiBanking_constants;

dgiBankingConstants::dgiBankingConstants() {
}

} // namespace

