/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef dgiBankingTypes_CONSTANTS_H
#define dgiBankingTypes_CONSTANTS_H

#include "dgiBankingTypes_types.h"

namespace dgi {

class dgiBankingTypesConstants {
 public:
  dgiBankingTypesConstants();

};

extern const dgiBankingTypesConstants g_dgiBankingTypes_constants;

} // namespace

#endif
