/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef dgiBanking_CONSTANTS_H
#define dgiBanking_CONSTANTS_H

#include "dgiBanking_types.h"

namespace dgi {

class dgiBankingConstants {
 public:
  dgiBankingConstants();

};

extern const dgiBankingConstants g_dgiBanking_constants;

} // namespace

#endif
