/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef dgiCommonTypes_CONSTANTS_H
#define dgiCommonTypes_CONSTANTS_H

#include "dgiCommonTypes_types.h"

namespace dgi {

class dgiCommonTypesConstants {
 public:
  dgiCommonTypesConstants();

};

extern const dgiCommonTypesConstants g_dgiCommonTypes_constants;

} // namespace

#endif
