/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "dgiCommonTypes_constants.h"

namespace dgi {

const dgiCommonTypesConstants g_dgiCommonTypes_constants;

dgiCommonTypesConstants::dgiCommonTypesConstants() {
}

} // namespace

