/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef dgiEncryption_CONSTANTS_H
#define dgiEncryption_CONSTANTS_H

#include "dgiEncryption_types.h"

namespace dgi {

class dgiEncryptionConstants {
 public:
  dgiEncryptionConstants();

};

extern const dgiEncryptionConstants g_dgiEncryption_constants;

} // namespace

#endif
