/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "dgiEncryption_constants.h"

namespace dgi {

const dgiEncryptionConstants g_dgiEncryption_constants;

dgiEncryptionConstants::dgiEncryptionConstants() {
}

} // namespace

