/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef dgiEncryptionTypes_CONSTANTS_H
#define dgiEncryptionTypes_CONSTANTS_H

#include "dgiEncryptionTypes_types.h"

namespace dgi {

class dgiEncryptionTypesConstants {
 public:
  dgiEncryptionTypesConstants();

};

extern const dgiEncryptionTypesConstants g_dgiEncryptionTypes_constants;

} // namespace

#endif
