/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "dgiEncryptionTypes_constants.h"

namespace dgi {

const dgiEncryptionTypesConstants g_dgiEncryptionTypes_constants;

dgiEncryptionTypesConstants::dgiEncryptionTypesConstants() {
}

} // namespace

