/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef dgiFolderLock_CONSTANTS_H
#define dgiFolderLock_CONSTANTS_H

#include "dgiFolderLock_types.h"

namespace dgi {

class dgiFolderLockConstants {
 public:
  dgiFolderLockConstants();

};

extern const dgiFolderLockConstants g_dgiFolderLock_constants;

} // namespace

#endif
