/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "dgiFolderLockTypes_constants.h"

namespace dgi {

const dgiFolderLockTypesConstants g_dgiFolderLockTypes_constants;

dgiFolderLockTypesConstants::dgiFolderLockTypesConstants() {
}

} // namespace

