/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "dgiFolderLock_constants.h"

namespace dgi {

const dgiFolderLockConstants g_dgiFolderLock_constants;

dgiFolderLockConstants::dgiFolderLockConstants() {
}

} // namespace

