/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef dgiSecureErase_CONSTANTS_H
#define dgiSecureErase_CONSTANTS_H

#include "dgiSecureErase_types.h"

namespace dgi {

class dgiSecureEraseConstants {
 public:
  dgiSecureEraseConstants();

};

extern const dgiSecureEraseConstants g_dgiSecureErase_constants;

} // namespace

#endif
