/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef dgiServiceManager_CONSTANTS_H
#define dgiServiceManager_CONSTANTS_H

#include "dgiServiceManager_types.h"

namespace dgi {

class dgiServiceManagerConstants {
 public:
  dgiServiceManagerConstants();

};

extern const dgiServiceManagerConstants g_dgiServiceManager_constants;

} // namespace

#endif
