/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "dgiSecureEraseTypes_constants.h"

namespace dgi {

const dgiSecureEraseTypesConstants g_dgiSecureEraseTypes_constants;

dgiSecureEraseTypesConstants::dgiSecureEraseTypesConstants() {
}

} // namespace

