/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "dgiSecureErase_constants.h"

namespace dgi {

const dgiSecureEraseConstants g_dgiSecureErase_constants;

dgiSecureEraseConstants::dgiSecureEraseConstants() {
}

} // namespace

