// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "DgiSecureErase.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::dgi;

class DgiSecureEraseHandler : virtual public DgiSecureEraseIf {
 public:
  DgiSecureEraseHandler() {
    // Your initialization goes here
  }

  void eraseFiles( ::dgi::AsyncResponse& _return, const  ::dgi::EraseList& _toErase) {
    // Your implementation goes here
    printf("eraseFiles\n");
  }

  void getState( ::dgi::DgiResult& _return, const  ::dgi::AsyncId _asyncId) {
    // Your implementation goes here
    printf("getState\n");
  }

  void getEraseState( ::dgi::EraseResponse& _return, const  ::dgi::AsyncId _asyncId) {
    // Your implementation goes here
    printf("getEraseState\n");
  }

  void eraseFile( ::dgi::DgiResult& _return, const std::string& _filepath) {
    // Your implementation goes here
    printf("eraseFile\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::apache::thrift::stdcxx::shared_ptr<DgiSecureEraseHandler> handler(new DgiSecureEraseHandler());
  ::apache::thrift::stdcxx::shared_ptr<TProcessor> processor(new DgiSecureEraseProcessor(handler));
  ::apache::thrift::stdcxx::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::apache::thrift::stdcxx::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::apache::thrift::stdcxx::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

