//
// Developer:
//				Burlutsky Stanislav
//				burluckij@gmail.com
//


#define WINDOWS_SERVICE_NAME		L"DgiService"


#define THRIFT_SERVICE_BASE_PORT	2991
#define THRIFT_MAIN_PORT			(THRIFT_SERVICE_BASE_PORT + 0)
#define THRIFT_ENCRYPTION_PORT		(THRIFT_SERVICE_BASE_PORT + 1)
#define THRIFT_FLOCK_PORT			(THRIFT_SERVICE_BASE_PORT + 2)
#define THRIFT_ERASING_PORT			(THRIFT_SERVICE_BASE_PORT + 3)
#define THRIFT_BANKING_PORT			(THRIFT_SERVICE_BASE_PORT + 4)

#define DGI_LOCAL_DEBUG_NO_DRV      1

